# Generated by Django 4.2.1 on 2023-05-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_address', models.CharField(max_length=80)),
                ('p_post', models.CharField(max_length=70)),
            ],
        ),
    ]
