# Generated by Django 4.2.1 on 2023-05-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=140)),
                ('std_dept', models.CharField(max_length=20)),
                ('std_email', models.EmailField(max_length=30)),
                ('std_address', models.CharField(max_length=150)),
            ],
        ),
    ]
